{
 "title": "Cassandra Testbed",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Service Reponse Time (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*(avg(rate(istio_turbo_service_latency_time_ms_sum{response_code=\"200\"}[3m])/rate(istio_turbo_service_latency_time_ms_count{response_code=\"200\"}[3m])) by (destination_uid))",
     "legendFormat": "{{destination_uid}}"
    }
   ]
  },
  {
   "title": "Service QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(istio_turbo_service_request_count{response_code=\"200\"}[3m])) by (destination_uid)",
     "legendFormat": "{{destination_uid}}"
    }
   ]
  },
  {
   "title": "Cassandra Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:(write|read)latency:(50thpercentile|99thpercentile|max)\"})",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cassandra QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_stats{name=~\"org:apache:cassandra:metrics:table:(write|read)latency:oneminuterate\"}",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, 99p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:99thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, 99p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:99thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, 50p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:50thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, 50p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:50thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, max (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:max\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, max (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:max\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}