TWITTER_KEYSPACE = "maxtwitter"
TWITTER_TWEET_TABLE_NAME = "maxtweettable"
TWITTER_FRIEND_TABLE_NAME = "maxtweetfriendtable"

TWITTER_NEWS_FEED_COUNT = 10
TWITTER_TIMELINE_COUNT = 10
TWITTER_TOTAL_TIMELINE_COUNT = 50

TWITTER_MAX_FOLLOWS = 100
