# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import user_service_pb2 as user__service__pb2


class TwitterUserStub(object):
  """User interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/twitteruser.TwitterUser/GetUser',
        request_serializer=user__service__pb2.GetUserRequest.SerializeToString,
        response_deserializer=user__service__pb2.GetUserResponse.FromString,
        )
    self.CheckPassword = channel.unary_unary(
        '/twitteruser.TwitterUser/CheckPassword',
        request_serializer=user__service__pb2.CheckPasswordRequest.SerializeToString,
        response_deserializer=user__service__pb2.CheckPasswordResponse.FromString,
        )
    self.CheckSession = channel.unary_unary(
        '/twitteruser.TwitterUser/CheckSession',
        request_serializer=user__service__pb2.CheckSessionRequest.SerializeToString,
        response_deserializer=user__service__pb2.CheckSessionResponse.FromString,
        )
    self.RemoveSession = channel.unary_unary(
        '/twitteruser.TwitterUser/RemoveSession',
        request_serializer=user__service__pb2.RemoveSessionRequest.SerializeToString,
        response_deserializer=user__service__pb2.RemoveSessionResponse.FromString,
        )


class TwitterUserServicer(object):
  """User interface exported by the server.
  """

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckPassword(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TwitterUserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=user__service__pb2.GetUserRequest.FromString,
          response_serializer=user__service__pb2.GetUserResponse.SerializeToString,
      ),
      'CheckPassword': grpc.unary_unary_rpc_method_handler(
          servicer.CheckPassword,
          request_deserializer=user__service__pb2.CheckPasswordRequest.FromString,
          response_serializer=user__service__pb2.CheckPasswordResponse.SerializeToString,
      ),
      'CheckSession': grpc.unary_unary_rpc_method_handler(
          servicer.CheckSession,
          request_deserializer=user__service__pb2.CheckSessionRequest.FromString,
          response_serializer=user__service__pb2.CheckSessionResponse.SerializeToString,
      ),
      'RemoveSession': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveSession,
          request_deserializer=user__service__pb2.RemoveSessionRequest.FromString,
          response_serializer=user__service__pb2.RemoveSessionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'twitteruser.TwitterUser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
