# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friend_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='friend_service.proto',
  package='friend',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x66riend_service.proto\x12\x06\x66riend\"#\n\x10\x46olloweesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"&\n\x11\x46olloweesResponse\x12\x11\n\tfollowees\x18\x01 \x03(\x05\"3\n\x0e\x46ollowsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ollowee\x18\x02 \x01(\x05\"\x1f\n\x0f\x46ollowsResponse\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x32\x8a\x01\n\x06\x46riend\x12\x42\n\tFollowees\x12\x18.friend.FolloweesRequest\x1a\x19.friend.FolloweesResponse\"\x00\x12<\n\x07\x46ollows\x12\x16.friend.FollowsRequest\x1a\x17.friend.FollowsResponse\"\x00\x62\x06proto3')
)




_FOLLOWEESREQUEST = _descriptor.Descriptor(
  name='FolloweesRequest',
  full_name='friend.FolloweesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='friend.FolloweesRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)


_FOLLOWEESRESPONSE = _descriptor.Descriptor(
  name='FolloweesResponse',
  full_name='friend.FolloweesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='followees', full_name='friend.FolloweesResponse.followees', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=107,
)


_FOLLOWSREQUEST = _descriptor.Descriptor(
  name='FollowsRequest',
  full_name='friend.FollowsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='friend.FollowsRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followee', full_name='friend.FollowsRequest.followee', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=160,
)


_FOLLOWSRESPONSE = _descriptor.Descriptor(
  name='FollowsResponse',
  full_name='friend.FollowsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='done', full_name='friend.FollowsResponse.done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['FolloweesRequest'] = _FOLLOWEESREQUEST
DESCRIPTOR.message_types_by_name['FolloweesResponse'] = _FOLLOWEESRESPONSE
DESCRIPTOR.message_types_by_name['FollowsRequest'] = _FOLLOWSREQUEST
DESCRIPTOR.message_types_by_name['FollowsResponse'] = _FOLLOWSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FolloweesRequest = _reflection.GeneratedProtocolMessageType('FolloweesRequest', (_message.Message,), dict(
  DESCRIPTOR = _FOLLOWEESREQUEST,
  __module__ = 'friend_service_pb2'
  # @@protoc_insertion_point(class_scope:friend.FolloweesRequest)
  ))
_sym_db.RegisterMessage(FolloweesRequest)

FolloweesResponse = _reflection.GeneratedProtocolMessageType('FolloweesResponse', (_message.Message,), dict(
  DESCRIPTOR = _FOLLOWEESRESPONSE,
  __module__ = 'friend_service_pb2'
  # @@protoc_insertion_point(class_scope:friend.FolloweesResponse)
  ))
_sym_db.RegisterMessage(FolloweesResponse)

FollowsRequest = _reflection.GeneratedProtocolMessageType('FollowsRequest', (_message.Message,), dict(
  DESCRIPTOR = _FOLLOWSREQUEST,
  __module__ = 'friend_service_pb2'
  # @@protoc_insertion_point(class_scope:friend.FollowsRequest)
  ))
_sym_db.RegisterMessage(FollowsRequest)

FollowsResponse = _reflection.GeneratedProtocolMessageType('FollowsResponse', (_message.Message,), dict(
  DESCRIPTOR = _FOLLOWSRESPONSE,
  __module__ = 'friend_service_pb2'
  # @@protoc_insertion_point(class_scope:friend.FollowsResponse)
  ))
_sym_db.RegisterMessage(FollowsResponse)



_FRIEND = _descriptor.ServiceDescriptor(
  name='Friend',
  full_name='friend.Friend',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=196,
  serialized_end=334,
  methods=[
  _descriptor.MethodDescriptor(
    name='Followees',
    full_name='friend.Friend.Followees',
    index=0,
    containing_service=None,
    input_type=_FOLLOWEESREQUEST,
    output_type=_FOLLOWEESRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Follows',
    full_name='friend.Friend.Follows',
    index=1,
    containing_service=None,
    input_type=_FOLLOWSREQUEST,
    output_type=_FOLLOWSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRIEND)

DESCRIPTOR.services_by_name['Friend'] = _FRIEND

# @@protoc_insertion_point(module_scope)
