# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweet_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tweet_service.proto',
  package='tweet',
  syntax='proto3',
  serialized_pb=_b('\n\x13tweet_service.proto\x12\x05tweet\"0\n\x0cTweetRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"!\n\rTweetResponse\x12\x10\n\x08tweet_id\x18\x01 \x01(\x05\"\"\n\x0fNewsfeedRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"7\n\x10NewsfeedResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\t\"5\n\x0fTimelineRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tfollowees\x18\x02 \x03(\x05\"H\n\x10TimelineResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t2\xbf\x01\n\x05Tweet\x12\x34\n\x05Tweet\x12\x13.tweet.TweetRequest\x1a\x14.tweet.TweetResponse\"\x00\x12?\n\x08Newsfeed\x12\x16.tweet.NewsfeedRequest\x1a\x17.tweet.NewsfeedResponse\"\x00\x30\x01\x12?\n\x08Timeline\x12\x16.tweet.TimelineRequest\x1a\x17.tweet.TimelineResponse\"\x00\x30\x01\x62\x06proto3')
)




_TWEETREQUEST = _descriptor.Descriptor(
  name='TweetRequest',
  full_name='tweet.TweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tweet.TweetRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='tweet.TweetRequest.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=78,
)


_TWEETRESPONSE = _descriptor.Descriptor(
  name='TweetResponse',
  full_name='tweet.TweetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweet_id', full_name='tweet.TweetResponse.tweet_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=113,
)


_NEWSFEEDREQUEST = _descriptor.Descriptor(
  name='NewsfeedRequest',
  full_name='tweet.NewsfeedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tweet.NewsfeedRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=149,
)


_NEWSFEEDRESPONSE = _descriptor.Descriptor(
  name='NewsfeedResponse',
  full_name='tweet.NewsfeedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='tweet.NewsfeedResponse.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='tweet.NewsfeedResponse.created_at', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=206,
)


_TIMELINEREQUEST = _descriptor.Descriptor(
  name='TimelineRequest',
  full_name='tweet.TimelineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tweet.TimelineRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followees', full_name='tweet.TimelineRequest.followees', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=261,
)


_TIMELINERESPONSE = _descriptor.Descriptor(
  name='TimelineResponse',
  full_name='tweet.TimelineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tweet.TimelineResponse.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='tweet.TimelineResponse.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='tweet.TimelineResponse.created_at', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=335,
)

DESCRIPTOR.message_types_by_name['TweetRequest'] = _TWEETREQUEST
DESCRIPTOR.message_types_by_name['TweetResponse'] = _TWEETRESPONSE
DESCRIPTOR.message_types_by_name['NewsfeedRequest'] = _NEWSFEEDREQUEST
DESCRIPTOR.message_types_by_name['NewsfeedResponse'] = _NEWSFEEDRESPONSE
DESCRIPTOR.message_types_by_name['TimelineRequest'] = _TIMELINEREQUEST
DESCRIPTOR.message_types_by_name['TimelineResponse'] = _TIMELINERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TweetRequest = _reflection.GeneratedProtocolMessageType('TweetRequest', (_message.Message,), dict(
  DESCRIPTOR = _TWEETREQUEST,
  __module__ = 'tweet_service_pb2'
  # @@protoc_insertion_point(class_scope:tweet.TweetRequest)
  ))
_sym_db.RegisterMessage(TweetRequest)

TweetResponse = _reflection.GeneratedProtocolMessageType('TweetResponse', (_message.Message,), dict(
  DESCRIPTOR = _TWEETRESPONSE,
  __module__ = 'tweet_service_pb2'
  # @@protoc_insertion_point(class_scope:tweet.TweetResponse)
  ))
_sym_db.RegisterMessage(TweetResponse)

NewsfeedRequest = _reflection.GeneratedProtocolMessageType('NewsfeedRequest', (_message.Message,), dict(
  DESCRIPTOR = _NEWSFEEDREQUEST,
  __module__ = 'tweet_service_pb2'
  # @@protoc_insertion_point(class_scope:tweet.NewsfeedRequest)
  ))
_sym_db.RegisterMessage(NewsfeedRequest)

NewsfeedResponse = _reflection.GeneratedProtocolMessageType('NewsfeedResponse', (_message.Message,), dict(
  DESCRIPTOR = _NEWSFEEDRESPONSE,
  __module__ = 'tweet_service_pb2'
  # @@protoc_insertion_point(class_scope:tweet.NewsfeedResponse)
  ))
_sym_db.RegisterMessage(NewsfeedResponse)

TimelineRequest = _reflection.GeneratedProtocolMessageType('TimelineRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMELINEREQUEST,
  __module__ = 'tweet_service_pb2'
  # @@protoc_insertion_point(class_scope:tweet.TimelineRequest)
  ))
_sym_db.RegisterMessage(TimelineRequest)

TimelineResponse = _reflection.GeneratedProtocolMessageType('TimelineResponse', (_message.Message,), dict(
  DESCRIPTOR = _TIMELINERESPONSE,
  __module__ = 'tweet_service_pb2'
  # @@protoc_insertion_point(class_scope:tweet.TimelineResponse)
  ))
_sym_db.RegisterMessage(TimelineResponse)



_TWEET = _descriptor.ServiceDescriptor(
  name='Tweet',
  full_name='tweet.Tweet',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=338,
  serialized_end=529,
  methods=[
  _descriptor.MethodDescriptor(
    name='Tweet',
    full_name='tweet.Tweet.Tweet',
    index=0,
    containing_service=None,
    input_type=_TWEETREQUEST,
    output_type=_TWEETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Newsfeed',
    full_name='tweet.Tweet.Newsfeed',
    index=1,
    containing_service=None,
    input_type=_NEWSFEEDREQUEST,
    output_type=_NEWSFEEDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Timeline',
    full_name='tweet.Tweet.Timeline',
    index=2,
    containing_service=None,
    input_type=_TIMELINEREQUEST,
    output_type=_TIMELINERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWEET)

DESCRIPTOR.services_by_name['Tweet'] = _TWEET

# @@protoc_insertion_point(module_scope)
