# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_service.proto',
  package='twitteruser',
  syntax='proto3',
  serialized_pb=_b('\n\x12user_service.proto\x12\x0btwitteruser\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"0\n\x0fGetUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"#\n\x0fGetUsersRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\x05\"!\n\x10GetUsersResponse\x12\r\n\x05names\x18\x01 \x03(\t\"9\n\x14\x43heckPasswordRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x15\x43heckPasswordResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0bsession_key\x18\x02 \x01(\t\";\n\x13\x43heckSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bsession_key\x18\x02 \x01(\t\"\"\n\x14\x43heckSessionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"+\n\x14RemoveSessionRequest\x12\x13\n\x0bsession_key\x18\x01 \x01(\t\"#\n\x15RemoveSessionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xab\x03\n\x0bTwitterUser\x12\x46\n\x07GetUser\x12\x1b.twitteruser.GetUserRequest\x1a\x1c.twitteruser.GetUserResponse\"\x00\x12I\n\x08GetUsers\x12\x1c.twitteruser.GetUsersRequest\x1a\x1d.twitteruser.GetUsersResponse\"\x00\x12X\n\rCheckPassword\x12!.twitteruser.CheckPasswordRequest\x1a\".twitteruser.CheckPasswordResponse\"\x00\x12U\n\x0c\x43heckSession\x12 .twitteruser.CheckSessionRequest\x1a!.twitteruser.CheckSessionResponse\"\x00\x12X\n\rRemoveSession\x12!.twitteruser.RemoveSessionRequest\x1a\".twitteruser.RemoveSessionResponse\"\x00\x62\x06proto3')
)




_GETUSERREQUEST = _descriptor.Descriptor(
  name='GetUserRequest',
  full_name='twitteruser.GetUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='twitteruser.GetUserRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=68,
)


_GETUSERRESPONSE = _descriptor.Descriptor(
  name='GetUserResponse',
  full_name='twitteruser.GetUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='twitteruser.GetUserResponse.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='twitteruser.GetUserResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=118,
)


_GETUSERSREQUEST = _descriptor.Descriptor(
  name='GetUsersRequest',
  full_name='twitteruser.GetUsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='twitteruser.GetUsersRequest.user_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=155,
)


_GETUSERSRESPONSE = _descriptor.Descriptor(
  name='GetUsersResponse',
  full_name='twitteruser.GetUsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='twitteruser.GetUsersResponse.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=190,
)


_CHECKPASSWORDREQUEST = _descriptor.Descriptor(
  name='CheckPasswordRequest',
  full_name='twitteruser.CheckPasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='twitteruser.CheckPasswordRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='twitteruser.CheckPasswordRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=249,
)


_CHECKPASSWORDRESPONSE = _descriptor.Descriptor(
  name='CheckPasswordResponse',
  full_name='twitteruser.CheckPasswordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='twitteruser.CheckPasswordResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='twitteruser.CheckPasswordResponse.session_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=307,
)


_CHECKSESSIONREQUEST = _descriptor.Descriptor(
  name='CheckSessionRequest',
  full_name='twitteruser.CheckSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='twitteruser.CheckSessionRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='twitteruser.CheckSessionRequest.session_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=368,
)


_CHECKSESSIONRESPONSE = _descriptor.Descriptor(
  name='CheckSessionResponse',
  full_name='twitteruser.CheckSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='twitteruser.CheckSessionResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=404,
)


_REMOVESESSIONREQUEST = _descriptor.Descriptor(
  name='RemoveSessionRequest',
  full_name='twitteruser.RemoveSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_key', full_name='twitteruser.RemoveSessionRequest.session_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=449,
)


_REMOVESESSIONRESPONSE = _descriptor.Descriptor(
  name='RemoveSessionResponse',
  full_name='twitteruser.RemoveSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='twitteruser.RemoveSessionResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=486,
)

DESCRIPTOR.message_types_by_name['GetUserRequest'] = _GETUSERREQUEST
DESCRIPTOR.message_types_by_name['GetUserResponse'] = _GETUSERRESPONSE
DESCRIPTOR.message_types_by_name['GetUsersRequest'] = _GETUSERSREQUEST
DESCRIPTOR.message_types_by_name['GetUsersResponse'] = _GETUSERSRESPONSE
DESCRIPTOR.message_types_by_name['CheckPasswordRequest'] = _CHECKPASSWORDREQUEST
DESCRIPTOR.message_types_by_name['CheckPasswordResponse'] = _CHECKPASSWORDRESPONSE
DESCRIPTOR.message_types_by_name['CheckSessionRequest'] = _CHECKSESSIONREQUEST
DESCRIPTOR.message_types_by_name['CheckSessionResponse'] = _CHECKSESSIONRESPONSE
DESCRIPTOR.message_types_by_name['RemoveSessionRequest'] = _REMOVESESSIONREQUEST
DESCRIPTOR.message_types_by_name['RemoveSessionResponse'] = _REMOVESESSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetUserRequest = _reflection.GeneratedProtocolMessageType('GetUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERREQUEST,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.GetUserRequest)
  ))
_sym_db.RegisterMessage(GetUserRequest)

GetUserResponse = _reflection.GeneratedProtocolMessageType('GetUserResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERRESPONSE,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.GetUserResponse)
  ))
_sym_db.RegisterMessage(GetUserResponse)

GetUsersRequest = _reflection.GeneratedProtocolMessageType('GetUsersRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERSREQUEST,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.GetUsersRequest)
  ))
_sym_db.RegisterMessage(GetUsersRequest)

GetUsersResponse = _reflection.GeneratedProtocolMessageType('GetUsersResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERSRESPONSE,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.GetUsersResponse)
  ))
_sym_db.RegisterMessage(GetUsersResponse)

CheckPasswordRequest = _reflection.GeneratedProtocolMessageType('CheckPasswordRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHECKPASSWORDREQUEST,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.CheckPasswordRequest)
  ))
_sym_db.RegisterMessage(CheckPasswordRequest)

CheckPasswordResponse = _reflection.GeneratedProtocolMessageType('CheckPasswordResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHECKPASSWORDRESPONSE,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.CheckPasswordResponse)
  ))
_sym_db.RegisterMessage(CheckPasswordResponse)

CheckSessionRequest = _reflection.GeneratedProtocolMessageType('CheckSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHECKSESSIONREQUEST,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.CheckSessionRequest)
  ))
_sym_db.RegisterMessage(CheckSessionRequest)

CheckSessionResponse = _reflection.GeneratedProtocolMessageType('CheckSessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHECKSESSIONRESPONSE,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.CheckSessionResponse)
  ))
_sym_db.RegisterMessage(CheckSessionResponse)

RemoveSessionRequest = _reflection.GeneratedProtocolMessageType('RemoveSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOVESESSIONREQUEST,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.RemoveSessionRequest)
  ))
_sym_db.RegisterMessage(RemoveSessionRequest)

RemoveSessionResponse = _reflection.GeneratedProtocolMessageType('RemoveSessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOVESESSIONRESPONSE,
  __module__ = 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:twitteruser.RemoveSessionResponse)
  ))
_sym_db.RegisterMessage(RemoveSessionResponse)



_TWITTERUSER = _descriptor.ServiceDescriptor(
  name='TwitterUser',
  full_name='twitteruser.TwitterUser',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=489,
  serialized_end=916,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='twitteruser.TwitterUser.GetUser',
    index=0,
    containing_service=None,
    input_type=_GETUSERREQUEST,
    output_type=_GETUSERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUsers',
    full_name='twitteruser.TwitterUser.GetUsers',
    index=1,
    containing_service=None,
    input_type=_GETUSERSREQUEST,
    output_type=_GETUSERSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckPassword',
    full_name='twitteruser.TwitterUser.CheckPassword',
    index=2,
    containing_service=None,
    input_type=_CHECKPASSWORDREQUEST,
    output_type=_CHECKPASSWORDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckSession',
    full_name='twitteruser.TwitterUser.CheckSession',
    index=3,
    containing_service=None,
    input_type=_CHECKSESSIONREQUEST,
    output_type=_CHECKSESSIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveSession',
    full_name='twitteruser.TwitterUser.RemoveSession',
    index=4,
    containing_service=None,
    input_type=_REMOVESESSIONREQUEST,
    output_type=_REMOVESESSIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERUSER)

DESCRIPTOR.services_by_name['TwitterUser'] = _TWITTERUSER

# @@protoc_insertion_point(module_scope)
