apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: {{ .Release.Namespace }}
  labels:
    name: locust
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locust
      role: worker
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust-worker
          image: {{ .Values.image.repository }}/locust:{{ .Values.image.locustTag }}
          imagePullPolicy: {{ .Values.image.locustPullPolicy }}
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: {{ .Values.locust.target_host | quote}}
            - name: MAX_TWITTER_USER_ID
              value: {{ .Values.locust.max_twitter_user_id | quote}}
            - name: MAX_NUM_FOLLOWS
              value: {{ .Values.locust.max_num_follows | quote}}
            - name: VISIT_RATE_TWEET
              value: {{ .Values.locust.visit_rate_tweet | quote}}
            - name: VISIT_RATE_TIMELINE
              value: {{ .Values.locust.visit_rate_timeline | quote}}
            - name: VISIT_RATE_NEWSFEED
              value: {{ .Values.locust.visit_rate_newsfeed | quote}}
            - name: VISIT_RATE_FOLLOW
              value: {{ .Values.locust.visit_rate_follow | quote}}
            - name: NEXT_REQUEST_MIN_WAIT_MS
              value: {{ .Values.locust.next_request_min_wait_ms | quote}}
            - name: NEXT_REQUEST_MAX_WAIT_MS
              value: {{ .Values.locust.next_request_max_wait_ms | quote}}
            - name: ENABLE_TIME_SLOT_PROBABILITY
              value: {{ .Values.locust.enable_time_slot_probability | quote}}
            - name: LOCUSTFILE
              value: {{ .Values.locust.locustfile }}
            - name: TIME_SLOT_PROBABILITY
              value: {{ .Values.locust.time_slot_probability | quote}}
            - name: TIME_SLOT_PROBABILITY_STEP_IN_MIN
              value: {{ .Values.locust.time_slot_probability_step_in_min | quote}}
