apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-cass-friend
  namespace: {{ .Release.Namespace }}
  labels:
    app: twitter-cass-friend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: twitter-cass-friend
  template:
    metadata:
      labels:
        app: twitter-cass-friend
    spec:
      imagePullSecrets:
        - name: artifactory-registry-secret
      containers:
      - name: twitter-cass-friend
        image: {{ .Values.image.repository }}/twitter-cass-friend:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.grpc.max_connection_age_ms }}
        args:
        - --grpc-max-connection-age-ms {{ .Values.grpc.max_connection_age_ms }}
{{- end }}
        ports:
          - containerPort: 50053
        env:
        - name: CASSANDRA_HOST_ADDRESS
          value: cassandra
{{- if .Values.grpc.debug }}
        - name: GRPC_VERBOSITY
          value: DEBUG
{{- if .Values.grpc.trace }}
        - name: GRPC_TRACE
          value: {{ .Values.grpc.trace | quote }}
{{- end }}
{{- end }}
{{- if .Values.instana.enabled }}
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-cass-friend
  namespace: {{ .Release.Namespace }}
  labels:
    app: twitter-cass-friend
spec:
  type: ClusterIP
  ports:
    - port: 50053
      name: grpc-twitter-cass-friend
  selector:
    app: twitter-cass-friend
