# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tweet_service_pb2 as tweet__service__pb2


class TweetStub(object):
  """User interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Tweet = channel.unary_unary(
        '/tweet.Tweet/Tweet',
        request_serializer=tweet__service__pb2.TweetRequest.SerializeToString,
        response_deserializer=tweet__service__pb2.TweetResponse.FromString,
        )
    self.Newsfeed = channel.unary_stream(
        '/tweet.Tweet/Newsfeed',
        request_serializer=tweet__service__pb2.NewsfeedRequest.SerializeToString,
        response_deserializer=tweet__service__pb2.NewsfeedResponse.FromString,
        )
    self.Timeline = channel.unary_stream(
        '/tweet.Tweet/Timeline',
        request_serializer=tweet__service__pb2.TimelineRequest.SerializeToString,
        response_deserializer=tweet__service__pb2.TimelineResponse.FromString,
        )


class TweetServicer(object):
  """User interface exported by the server.
  """

  def Tweet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Newsfeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Timeline(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TweetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Tweet': grpc.unary_unary_rpc_method_handler(
          servicer.Tweet,
          request_deserializer=tweet__service__pb2.TweetRequest.FromString,
          response_serializer=tweet__service__pb2.TweetResponse.SerializeToString,
      ),
      'Newsfeed': grpc.unary_stream_rpc_method_handler(
          servicer.Newsfeed,
          request_deserializer=tweet__service__pb2.NewsfeedRequest.FromString,
          response_serializer=tweet__service__pb2.NewsfeedResponse.SerializeToString,
      ),
      'Timeline': grpc.unary_stream_rpc_method_handler(
          servicer.Timeline,
          request_deserializer=tweet__service__pb2.TimelineRequest.FromString,
          response_serializer=tweet__service__pb2.TimelineResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tweet.Tweet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
